const Consts = {
    SET_TOGGLE_MENU_SEARCH: 'SET_TOGGLE_MENU_SEARCH',
    SET_TOGGLE_MENU_CART: 'SET_TOGGLE_MENU_CART',
    GET_PRODUCTS: 'GET_PRODUCTS',
    SEND_PRODUCTS_CART: 'SEND_PRODUCTS_CART',
    SUM_AMOUNT_CART: 'SUM_AMOUNT_CART',
    MINUS_AMOUNT_CART: 'MINUS_AMOUNT_CART',
    DELETE_PRODUCT_CART: 'DELETE_PRODUCT_CART',
    SUM_QUANTITY_CART: 'SUM_QUANTITY_CART'
}
export default Consts 